version: "3.8"
services:
  excellent-catalog-service:
    depends_on:
      - excellent-postgres
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://excellent-postgres:5432/excellentdb_catalog
      - SPRING_PROFILES_ACTIVE=demo
  
  excellent-postgres:
    image: "postgres:15.3"
    container_name: "excellent-postgres"
    ports:
      - 5432:5432
    environment:
      - POSGRES_USER=postgres
      - POSTGRES_PASSWORD=chiskien
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  excellent-order-service:
    depends_on:
      - excellent-postgres
    image: "order-service"
    container_name: "order-service"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8002
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - EXCELLENT_CATALOG_SERVICE_URI=http://excellent-catalog-service:9001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://excellent-postgres:5432/excellentdb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://excellent-postgres:5432/excellentdb_order

  excellent-config-service: 
    image: "config-service"
    container_name: "config-service"
    ports:
      - 8888:8888
      - 9888:9888
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=988

  excellent-redis:
    image: "redis:7.2"
    container_name: "excellent-redis"
    ports:
      - 6379:6379

  excellent-edge-service:
    depends_on:
      - excellent-redis
    image: "edge-service"
    container_name: "edge-service"
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
      - EXCELLENT_CATALOG_SERVICE_URI=http://excellent-catalog-service:9001
      - EXCELLENT_ORDER_SERVICE_URI=http://excellent-order-service:9002
      - SPRING_CLOUD_CONFIG_URI=http://excellent-config-service:8888
      - SPRING_REDIS_HOST=excellent-redis

  excellent-rabbitmq:
    image: rabbitmq:3.12-management
    container_name: excellent-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf 

  excellent-keycloak:  # Section describing the KeyCloak Container
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: "excellent-keycloak"
    command: start-dev --import-realm # start keycloak in development mode (using an embedded database)
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:  # credentials
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - 8080:8080
