version: "3.8"
services:
  excellent-bookshop:
    depends_on:
      - excellent-postgres
    image: "excellent-bookshop"
    container_name: "excellent-bookshop"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://excellent-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=demo
  
  excellent-postgres:
    image: "postgres:15.3"
    container_name: "excellent-postgres"
    ports:
      - 5432:5432
    environment:
      - POSGRES_USER=postgres
      - POSTGRES_PASSWORD=chiskien
      - POSTGRES_DB=polardb_catalog

  config-service: 
    image: "config-service:0.0.1-SNAPSHOT"
    container_name: "config-service"
    ports:
      - 8888:8888
      - 9888:9888
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888
    