apiVersion: apps/v1
kind: Deployment
metadata:
  name: excellent-postgres
  labels:
    db: excellent-postgres
spec:
  selector:
    matchLabels:
      db: excellent-postgres
  template:
    metadata:
      labels:
        db: excellent-postgres
    spec:
      containers:
        - name: excellent-postgres
          image: postgres:15.3
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: chiskien
            - name: POSTGRES_DB
              value: polardb_catalog
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi
---
apiVersion: v1
kind: Service
metadata:
  name: excellent-postgres
  labels:
    db: excellent-postgres
spec:
  type: ClusterIP
  selector:
    db: excellent-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432